### PR TITLE
Use relative paths instead of INIT_CWD in order to allow windows instalation

### PR DESCRIPTION
**Pull request by bltavares**
[WIP] Preparing for fixes while trying to run `radicle-upstream` on Windows 

I'm opening pull requests earlier to document the effort needed to run Radicle Upstream on Windows - but feel free to wait for them all finished to evaluate the effort to maintain support.

### CODE REVIEW

**Comment by NunoAlexandre** [comment]
valeu, @bltavares!

**Review by rudolfs — APPROVED** [review]

**Review by rudolfs — CHANGES_REQUESTED** [review]
Thanks for the contribution!

The change looks good, tested it locally against our `radicle-upstream` and `radicle-bins` repos and the assets get correctly copied.

As we aim to attribute all contributors properly per our [DCO](https://github.com/radicle-dev/radicle-upstream/blob/master/DCO), could you please force push your commit with a [signoff](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff)?

**Comment by bltavares** [comment]
Signed off 👍

**Review by rudolfs — APPROVED** [review]

**Review by xla — APPROVED** [review]
🍋 ↕️ 🌾 🌪

**Comment by rudolfs** [comment]
Merged in via https://github.com/radicle-dev/twemoji-svg-assets/commit/385779cc6553dabae86d25f6165d3096c1ab0406.

Thanks for the contribution @bltavares!

**Pull request closed without merging**
